{% set name = "nsight-compute" %}
{% set version = "2025.4.0.12" %}
{% set version_split = version.split(".")[0]+"."+version.split(".")[1]+"."+version.split(".")[2] %}
{% set cuda_version = "13.1" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/nsight_compute/{{ platform }}/nsight_compute-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 75fca7c10a73f76cec6e5d97dd48cd480806c9222632f5df5f53b19154c75e0e  # [linux64]
  sha256: e6d378cc697de0733ce9f62fd137233bfc525f5365337e5fd44ac831fe785a5e  # [aarch64]
  sha256: af37cee796b6e0911f08795643b5ada2121d424186661300b89de8e534cce5f6  # [win]

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
    - alsa-lib             # [linux]
    - dbus                 # [linux]
    - expat
    - fontconfig
    - freetype
    - libglvnd-devel       # [linux]
    - libopengl-devel      # [linux]
    - krb5
    - libglib
    - libxcb
    - libxkbcommon         # [linux]
    - libxkbfile           # [linux]
    - libzlib
    - nspr                 # [linux]
    - nss                  # [linux]
    - wayland              # [linux]
    - xcb-util-cursor      # [linux]
    - xcb-util-image       # [linux]
    - xcb-util-keysyms     # [linux]
    - xcb-util-keysyms     # [linux]
    - xcb-util-renderutil  # [linux]
    - xcb-util-wm          # [linux]
    - xorg-libice          # [linux]
    - xorg-libsm           # [linux]
    - xorg-libx11          # [linux]
    - xorg-libxcomposite   # [linux]
    - xorg-libxdamage      # [linux]
    - xorg-libxext         # [linux]
    - xorg-libxfixes       # [linux]
    - xorg-libxrandr       # [linux]
    - xorg-libxrender      # [linux]
    - xorg-libxtst         # [linux]
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
    - {{ pin_compatible("xorg-libxcomposite", max_pin="x.x") }}  # [linux]
    - {{ pin_compatible("xorg-libxdamage", max_pin="x.x") }}     # [linux]
    - {{ pin_compatible("xorg-libxfixes", max_pin="x.x") }}      # [linux]
    - {{ pin_compatible("xorg-libxrandr", max_pin="x.x") }}      # [linux]
    - {{ pin_compatible("xorg-libxtst", max_pin="x.x") }}        # [linux]
    - {{ pin_compatible("libxkbfile", max_pin="x.x") }}          # [linux]
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  commands:
    - test -L $PREFIX/bin/ncu                                                  # [linux]
    - test -L $PREFIX/bin/ncu-ui                                               # [linux64 or aarch64]
    - if not exist %LIBRARY_PREFIX%\nsight-compute exit 1                      # [win]
    - if exist %LIBRARY_PREFIX%\nsight-compute\{{ version_split }}\lib exit 1  # [win]
    - if not exist %PREFIX%\Scripts\ncu.bat exit 1                             # [win]
    - ncu --version                                                            # [build_platform == target_platform]
    # ncu-ui test can be enabled for aarch64 once GLIBC 2.28 is made available
    # https://github.com/conda-forge/conda-forge.github.io/issues/1941
    # ncu-ui test is currently failing on linux64 as well due to missing x11 libs
    # https://github.com/conda-forge/nsight-compute-feedstock/issues/26
    # - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'ncu-ui --help-all'            # [linux64]

about:
  home: https://developer.nvidia.com/nsight-compute
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: NVIDIA Nsight Compute is an interactive kernel profiler for CUDA applications
  description: |
    NVIDIA Nsight Compute is an interactive kernel profiler for CUDA
    applications. It provides detailed performance metrics and API
    debugging via a user interface and command line tool.
  doc_url: https://docs.nvidia.com/nsight-compute/NsightCompute/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
